### ISSUE TITLE
Symbian S60v3 support

### ISSUE THREAD

**Issue by baumschubser** [kutegram/client#3]
Hi there, kutegram is amazing stuff! I was just wondering what it would take to compile the project with Qt 4.6.3 in order to have Kutegram on my S60v3 device. 

I imagine UI modifications are necessary, but work can only start once the target is building.

I tried to copy Symbian1Qt463 in the client folder and modify buildSymbian.bat accordingly, but that did not work out.
With Qt Creator I can only compile the desktop version, both 4.7.3 and 4.6.3 fail.

**Comment by twlswan** [comment]
+1, having kutegram working s60v3 would be amazing
tagging @curoviyxru  

edit: in the telegram group (@kutegramchat) he said: "it won't start on Symbian 9.2/9.3 even with build for Qt 4.6, I don't know why it errors for now."
reaaally hoping he'll find a fix lol

**Comment by baumschubser** [comment]
I can build with Qt 4.6.3 now. But when I start Kutegram I only get the message "Menu: Feature not supported" (tested with Nokia C5-00 and Nokia E51).

**Comment by curoviyxru** [comment]
Problem caused by third-party libraries that use C/C++ headers, I think.

**Comment by curoviyxru** [comment]
Yeah, It caused by CryptoPP and libqrencode, as I said before.
